kind: pipeline
name: stormCI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Setup&Build
    image: ubuntu:18.04
    commands:
      - cd $HOME
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio sudo
      - git config --global user.name "danascape"
      - git config --global user.email "danascape@gmail.com"
      - git config --global color.ui false
      - mkdir os && cd os
      - curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | sh
      - repo init -u https://github.com/StormBreaker-Infrastructure/kernel_manifest -b main --depth 1
      - repo sync
