kind: pipeline
name: stormCI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: Setup
    image: ubuntu:18.04
    commands:
      - cd $HOME
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio
      - git config --global user.name "danascape"
      - git config --global user.email "danascape@gmail.com"
      - git config --global color.ui false
