kind: pipeline
name: stormCI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&kramel
    image: starlight2834/ci_docker:latest
    environment:
      BRANCH:
        from_secret: branch
      DEVICE:
        from_secret: device
      GITHUB_TOKEN:
        from_secret: git
    commands:
      - cd $HOME
      - git config --global user.name "danascape"
      - git config --global user.email "danascape@gmail.com"
      - git config --global color.ui false
      - echo $DEVICE
      - echo $BRANCH
