kind: pipeline
name: stormCI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&kramel
    image: starlight2834/ci_docker:latest
    commands:
      - cd $HOME
      - git config --global user.name "danascape"
      - git config --global user.email "danascape@gmail.com"
      - git config --global color.ui false
      - apt update && apt-get install -y build-essential bc python curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev clang flex bison cpio
      - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
      - git clone https://github.com/danascape/sb-scripts
      - cd sb-scripts
      - source build.sh $DEVICE $BRANCH
