version: 2.1
parameters:
  device:
    type: string
    default: "none"
  branch:
    type: string
    default: "master"

jobs:
  setup:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison device-tree-compiler sudo
           git config --global user.name "danascape"
           git config --global user.email "danascape@gmail.com"
           git config --global color.ui false
           mkdir os && cd os
           curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | sh
           repo init -u https://github.com/StormBreaker-Infrastructure/kernel_manifest -b main --depth 1
           repo sync
           source build/envsetup.sh
           setupDevice X00P
           buildDefconfig
           buildKernelImage

workflows:
  version: 2.1
  cooking:
    jobs:
      - setup
